#!/usr/bin/python3

import ctypes
import sys

clibrary = ctypes.CDLL("./libfactors.so")
clibrary.find_factors.argtypes = [ctypes.c_long]

def factorize():

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    try:
        with open(sys.argv[1], 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    for line in lines:
        N = int(line.strip())
        clibrary.find_factors(N)

if __name__ == "__main__":
    factorize()