#!/usr/bin/python3

import ctypes
import sys

def factorize():
    clibrary = ctypes.CDLL("./libfactorize.so")
    clibrary.find_factors.argtypes = [ctypes.c_long]

    with open(sys.argv[1]) as f:
        line = f.readline().strip()
        while line != '':
            N = int(line)
            clibrary.find_factors(N)
            line = f.readline()

if __name__ == "__main__":
    factorize()