#!/usr/bin/python3

from cfunc import clibrary
import time
import sys

if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start_time = time.time()

    for line in lines:
        num = int(line.strip())
        factors = clibrary.factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()