#!/usr/bin/python3

import time
import sys

import ctypes
import os

path = os.getcwd()
clibrary = ctypes.CDLL(os.path.join(path, 'libfactorize.so'))

clibrary.factorize.restype = ctypes.POINTER(ctypes.c_uint64)
clibrary.factorize.argtypes = [ctypes.c_uint64]

if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    start_time = time.time()

    for line in lines:
        num = int(line.strip())
        factors = clibrary.factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()